version: '3'

services:
  # db:
  #   image: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     POSTGRES_USER: postgres
  #   ports:
  #     - "5432:5432"
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    env_file:
     - .env
    # depends_on:
    #   - db
networks:
  default:
    external:
      name: webproxy
# volumes:
#   postgres_data:
