# Generated by Django 2.2.1 on 2019-06-27 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlearning_app', '0003_auto_20190626_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='alpha',
            field=models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AlterField(
            model_name='problem',
            name='epochs',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='problem',
            name='gamma',
            field=models.FloatField(default=0.9, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2.0)]),
        ),
    ]
